# SPDX-License-Identifier: CC0-1.0

# This file contains configuration for YAMLlint [https://github.com/adrienverge/yamllint/].

---

yaml-files:
- '*.yml'

rules:
  anchors:
    level: error
  braces:
    level: error
  brackets:
    level: error
  colons:
    max-spaces-before:  0
    max-spaces-after:  -1
    level: error
  commas:
    max-spaces-before: -1
    min-spaces-after:   0
    max-spaces-after:  -1
    level: error
  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 1
    level: error
  comments-indentation:
    level: error
  document-end:
    present: true
    level: error
  document-start:
    present: true
    level: error
  empty-lines:
    max:       1
    max-start: 0
    max-end:   1
    level: error
  empty-values: disable
  float-values: disable
  hyphens:
    max-spaces-after: 1
    level: error
  indentation:
    indent-sequences: false
    spaces: 2
    level: error
  key-duplicates:
    level: error
  key-ordering: disable
  line-length: disable
  new-line-at-end-of-file: enable
  new-lines: disable
  octal-values: disable
  trailing-spaces:
    level: error
  truthy:
    level: error

...
